image: docker
services:
    - docker:dind    
build:
  script:
    - cd Docker
    - apk add --no-cache py-pip python-dev libffi-dev openssl-dev gcc libc-dev make
    - pip install docker-compose
    - docker-compose pull
    - docker-compose build 
test:
  before_script:
    - docker-compose version
  script:
    - docker-compo  up -d