version: "3.7"

services:
  sshd:
    image: ${COMPOSE_PROJECT_NAME}_sshd:latest
    build:
      context: ..
      dockerfile: ./Docker/sshd/Dockerfile
      args:
        - ROOT_PASSWORD=${SSH_ROOT}
    ports:
      - "9994:22"
    env_file:
      - ".env"
    networks:
      - ${PROJECT_NETWORKS}