version: "3.7"

networks:
  symfony-network:
    driver: ${NETWORKS_DRIVER}
    external:
      name: symfony-network
volumes:
  dbdata:
    driver: local

services:
  db:
    image: mysql:${DB_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    container_name: ${COMPOSE_PROJECT_NAME}_mysql_db
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - ${PROJECT_NETWORKS}
    restart: unless-stopped

  webserver:
    image: ${COMPOSE_PROJECT_NAME}_website_nginx:latest
    container_name: ${COMPOSE_PROJECT_NAME}_website_webserver
    env_file: 
      - .env
    build:
      context: ..
      dockerfile: ./Services/nginx/Dockerfile
    environment:
      XDEBUG_CONFIG: remote_host=192.168.1.2
    ports:
      - 9992:80
      - 9993:443
    links:
      - db:db
    volumes:
      - ${APP_CODE_PATH_HOST}/:${APP_CODE_PATH_CONTAINER}
      - ${APP_CODE_PATH_HOST}/.env_docker:/var/www/html/.env
    networks:
      - ${PROJECT_NETWORKS}

  php-fpm:
    image: ${COMPOSE_PROJECT_NAME}_website_application:latest
    container_name: ${COMPOSE_PROJECT_NAME}_website_php-fpm
    env_file:
      - .env
    build:
      context: ..
      dockerfile: ./Services/php-fpm/Dockerfile
      args:
        - APP_CODE_PATH=${APP_CODE_PATH_CONTAINER}
        - APP_GROUP=${APP_GROUP}
        - APP_GROUP_ID=${APP_GROUP_ID}
        - APP_USER=${APP_USER}
        - APP_USER_ID=${APP_USER_ID}
        - TARGET_PHP_VERSION=${PHP_VERSION}
        - TZ=${TIMEZONE}
    links:
      - db:db
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${APP_CODE_PATH_HOST}/.env_docker:/var/www/html/.env
    networks:
      - ${PROJECT_NETWORKS}