version: "3.7"

services:
  redis:
    image: redis
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    env_file:
      - .env
    ports:
      - 6379:6379
    networks:
      - ${PROJECT_NETWORKS}
    restart: unless-stopped
