name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # need checkout before using compose-action
      - name: Docker-compose build
        uses: isbang/compose-action@v1.0.0
        with:
          compose-file: './Services/docker-compose.yml'
          down-flags: '--volumes'
    
      
